export default {
  ACTION_INCREMENT: 'INCREMENT',
  ACTION_DECREMENT: 'DECREMENT',

  ACTION_LOADING_USERS: 'LOADING_USERS',
  ACTION_LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',

  ACTION_LOADING_USER: 'LOADING_USER',
  ACTION_LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
  ACTION_NEW_USER_CREATED: 'NEW_USER_CREATED',

  ACTION_CLEAN_EDIT_USED_DATA: 'CLEAN_EDIT_USED_DATA',

  ACTION_SAVING_USER: 'SAVING_USER',
  ACTION_SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
  ACTION_SAVE_USER_ERROR: 'SAVE_USER_ERROR',

  ACTION_USER_DELETED_SUCCESS: 'USER_DELETED_SUCCESS',
  ACTION_USER_DELETED_ERROR: 'USER_DELETED_ERROR',

  ACTION_LOGIN_STARTED: 'LOGIN_STARTED',
  ACTION_LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  ACTION_LOGIN_ERROR: 'LOGIN_ERROR',
  ACTION_LOGOUT: 'LOGOUT',

  ACTION_AUTH_CONFIRMED: 'AUTH_CONFIRMED',
  ACTION_AUTH_REJECTED: 'AUTH_REJECTED',
  ACTION_AUTH_TOKEN_NOT_FOUND: 'AUTH_TOKEN_NOT_FOUND',

  ACTION_UI_TOGGLE_DRAWER: 'UI_TOGGLE_DRAWER',
};