export default {
  ACTION_INCREMENT: 'INCREMENT',
  ACTION_DECREMENT: 'DECREMENT',

  ACTION_LOADING_USERS: 'LOADING_USERS',
  ACTION_LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',

  ACTION_LOADING_USER: 'LOADING_USER',
  ACTION_LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
};