export default {
  ACTION_INCREMENT: 'INCREMENT',
  ACTION_DECREMENT: 'DECREMENT',

  ACTION_LOADING_USERS: 'LOADING_USERS',
  ACTION_LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS',

  ACTION_LOADING_USER: 'LOADING_USER',
  ACTION_LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',

  ACTION_SAVING_USER: 'SAVING_USER',
  ACTION_SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',

  ACTION_LOGIN_STARTED: 'LOGIN_STARTED',
  ACTION_LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  ACTION_LOGIN_ERROR: 'LOGIN_ERROR',
  ACTION_LOGOUT: 'LOGOUT',
};